-- INSERT INTO burger (name, devoured) VALUES ('Cheeseburger', true);
-- INSERT INTO burger (name) VALUES ('Swiss Cheddar');
-- INSERT INTO burger (name) VALUES ('Ultimate Bacon');
-- INSERT INTO burger (name, devoured) VALUES ('Southwest Onion Ring', true);
-- INSERT INTO burger (name) VALUES ('Jethro Burger');
-- INSERT INTO burger (name, devoured) VALUES ('Whiplash Veggie', true);
